### ISSUE TITLE
Bloodmallet site isn't displaying % Damage Per Second, only Absolute Values

### ISSUE THREAD

**Issue by Shablamin** [Bloodmallet/bloodmallet_web_frontend#101]
Bloodmallet site isn't displaying % Damage Per Second, only Absolute Values. There is also an issue with some trinkets having Zero Absolute value as well.

Was working up until recently, tested on 3 different devices and networks.

**Comment by Bloodmallet** [comment]
Greetings,
please provide a link to a broken chart.
