### ISSUE TITLE
feral druid

### ISSUE THREAD

**Issue by ukf-kristofnogely** [Bloodmallet/bloodmallet_web_frontend#103]
talents and secondary stat distribution hasnt updated, the latter may be caused by the talents, since there was a change at the base of the tree, more than half of it is missing and showing feral to have a max potential at 30k dps at best, while other classes have 70-90k.
Also trinkets are getting insane values because of the raw damage of some items and the poor base dps of the sims
![trinkets](https://user-images.githubusercontent.com/116210093/215349365-09070bd4-1fa2-4926-b774-372252cff44e.PNG)
![talents](https://user-images.githubusercontent.com/116210093/215349367-4ad2b718-2bad-4b9d-8ec4-7b128cad8602.PNG)

Please have a look at it, thank You in advance

**Comment by Bloodmallet** [comment]
Thank you for the report. The data regenration of today has fixed the mentioned issues.
