### ISSUE TITLE
Heart of Thunder is using wrong item id

### ISSUE THREAD

**Issue by ljosberinn** [Bloodmallet/bloodmallet_web_frontend#107]
![image](https://github.com/Bloodmallet/bloodmallet_web_frontend/assets/29307652/0bbc58f9-ebeb-4dfc-8563-17d3cde929a8)

links to https://www.wowhead.com/item=56370/heart-of-thunder&ilvl=411 but it should be https://www.wowhead.com/item=133246/heart-of-thunder?ilvl=411

and the sims for it are accordingly low

https://bloodmallet.com/chart/paladin/protection/trinkets/castingpatchwerk (3rd last) which is understandable since... its the wrong trinket

**Comment by Bloodmallet** [comment]
Thank you for the ticket. This will be fixed with the next data regeneration.
