### ISSUE TITLE
is this an item tooltip bug or data bug that nobody ever noticed?

### ISSUE THREAD

**Issue by pharrowboy** [Bloodmallet/bloodmallet_web_frontend#108]
the trinkets that come from the refreshed dungeons show incorrect data on both wowhead and bloodmallet. 

for example this trinket link that shows at ilvl 411 it gives 660 primary stat is actually in fact incorrect because at 250 ilvl or 350 ilvl, it shows the same amount of primary stat. and at 447 ilvl it shows 660 primary stat on wowhead. 

https://www.wowhead.com/item=193743/irideus-fragment?ilvl=411#comments
https://www.wowhead.com/item=193743/irideus-fragment?ilvl=447#comments
wowheads data for old trinkets isnt scaling right. which leads to believe the sims are not calculating correctly. how do the sims know whats better if wowhead themselves do not know? i have no clue how to report this to wowhead but its worth looking into imo, just in case!

the irideus fragment inside the actual game at item level 437 says:

Irideus Fragment
Item Level 437
Binds when picked up
Unique-Equipped
Trinket
+597 Mastery
Use: Gain the Titans' crumbling power, increasing Agility by 4,713, reduced each time you use an ability. Lasts 20 sec. (3 Min Cooldown)

**Comment by Bloodmallet** [comment]
Greetings,
thank you for the report. I forwarded the info to wowhead.

Additionally how many stats a buff in SimulationCraft provides can be checked in the html report when looking further into the buff by opening the section.

Itemlevel 411: 
![grafik](https://github.com/Bloodmallet/bloodmallet_web_frontend/assets/9075987/90e4fd90-9a57-4811-9274-1878e8576a56)

Itemlevel 437:
![grafik](https://github.com/Bloodmallet/bloodmallet_web_frontend/assets/9075987/75a4efd6-132f-4905-a768-06527a1822bb)

Check the amount in the bottom right corner of the images.

**Comment by Bloodmallet** [comment]
I got the feedback, that tooltips are now rendered with itemlevel specific effect values. I'm closing this ticket. Please re-open it in case the issue pops up again.
