### ISSUE TITLE
Retribution Paladin Power Infusion support not detected

### ISSUE THREAD

**Issue by cremor** [Bloodmallet/bloodmallet_web_frontend#109]
Power Infusion support was added to the Retribution Paladin APL in https://github.com/simulationcraft/simc/commit/00f508e12e4a8d62b920b51d2c96c7a7274662ef but bloodmallet still says "No APL support." on https://bloodmallet.com/chart/power_infusion

**edit:** I just noticed that the table uses an older SimC version than the charts above. So that would explain it. But the point below is still valid.

Also, all specs link to a T29 profile in that table. The links should be upated to the T30 profiles. (And if bloodmallet actually still uses the T29 profiles for the charts than that should be updated too!)

**Comment by Bloodmallet** [comment]
Greetings,
thank you for creating this issue.

I'm updating the Power Infusion table now.

The link to the T29 profiles was wrong. The charts use T30 profiles for alle data generation. This will be fixed with the next website update.

**Comment by Bloodmallet** [comment]
The above commit fixes the raised issue.
