### ISSUE TITLE
Elemental shaman talent points (Patchwerk 5)

### ISSUE THREAD

**Issue by Maromortis** [Bloodmallet/bloodmallet_web_frontend#114]
![image](https://github.com/Bloodmallet/bloodmallet_web_frontend/assets/154746429/543f62da-f187-4492-be5a-842e6c666468)

As you can see the talent Lava Surge is selected without the previous talent, either Refreshing Waves or Primodial Bond being selected.

**Comment by Maromortis** [comment]
Enhancement has a similar problem:
![image](https://github.com/Bloodmallet/bloodmallet_web_frontend/assets/154746429/92f6a841-4379-4aec-a41a-760ae23d815e)

**Comment by Bloodmallet** [comment]
Sorry about missing this issue.

SimulationCraft can be run with any talent combination. There are no path-restrictions like ingame. So pointless non-dps talents can get skipped if the profile maintainer decides to do so.

This also allows impossible talent combinations by acccident. So checking for validity is always a good idea.
