### ISSUE TITLE
Devastation Evoker Phials chart not showing up on Casting Patchwerk 1 target

### ISSUE THREAD

**Issue by peytontw** [Bloodmallet/bloodmallet_web_frontend#115]
Devastation Evoker Phials chart not showing up on Casting Patchwerk 1 target. See the following link:

[https://bloodmallet.com/chart/evoker/devastation/phials/castingpatchwerk](https://bloodmallet.com/chart/evoker/devastation/phials/castingpatchwerk)

![Bloodmallet Bug](https://github.com/Bloodmallet/bloodmallet_web_frontend/assets/31866157/dd066a95-94e0-4566-a211-37bf93b12990)

**Comment by Bloodmallet** [comment]
Sorry about the delay. Closing the issue, because data is present now.
