### ISSUE TITLE
embellishment sims

### ISSUE THREAD

**Issue by mischief** [Bloodmallet/bloodmallet_web_frontend#116]
would be interesting to be able to see, for example, dreamtender's charm vs blue silken lining, similar to how weapon enchantment charts are shown.

this would likely require forcing the sim to have 1/2 crafted pieces.

**Comment by Bloodmallet** [comment]
Greetings,
I share the want to have embellishment simulations, but decided against them. When changing embellishments players ususally also change other items to shuffle their secondaries around. So a broad simulation like the charts here would either 
- not do this kind of optimization, which would mean the actual value of the embellishments could be larger OR
- do this kind of optimization which would mean a hell of a lot more required simulations to automatically optimize the profile for each embellishment

Neither struck me as a good.
