### ISSUE TITLE
SimulationCraft links point to the dragonflight branch

### ISSUE THREAD

**Issue by cremor** [Bloodmallet/bloodmallet_web_frontend#120]
It looks like all links to the SimulationCraft repository point to the "dragonflight" branch. Please update the links to point to the "thewarwithin" branch.

edit: Because I just noticed it, the link to your repository in ""tier appropriate" [fallback profile](https://github.com/Bloodmallet/bloodytools/tree/dev/fallback_profiles)" also points to a non existant branch.

**Comment by Bloodmallet** [comment]
Thank you for raising the issue. I'm fixing all these links.
