### ISSUE TITLE
Line for compare isn't aligned properly.

### ISSUE THREAD

**Issue by Shamainy** [Bloodmallet/bloodmallet_web_frontend#121]
![image](https://github.com/user-attachments/assets/0b74389e-7c1b-4b14-9c96-a1686b529618)

The line when you click on something to compare with everything else isn't lined up properly. Check screenshot.

**Comment by Bloodmallet** [comment]
Fix is rolling out. In a few minutes please hard-refresh the page (usually Ctrl + F5) and try again. Let me know if this fixed the issue for you.

**Comment by Shamainy** [comment]
> Fix is rolling out. In a few minutes please hard-refresh the page (usually Ctrl + F5) and try again. Let me know if this fixed the issue for you.

Yes it's working just fine now!

**Comment by Bloodmallet** [comment]
Thank you for the report.
