### ISSUE TITLE
MM Hunter using impossible build for sims

### ISSUE THREAD

**Issue by Dahpeht** [Bloodmallet/bloodmallet_web_frontend#123]
Title.

There's several spots in the talent tree that has nodes picked without having the previous node. The sims are wildly inaccurate to how a trinket actually performs, since it is simming with an impossible selection of talents. 

![image_2024-11-12_100327652](https://github.com/user-attachments/assets/1ecc1a83-c1a6-4459-8f4f-3f25bdc690dd)

**Comment by Bloodmallet** [comment]
Greetings,
please provide the link to the chart and your input.

**Comment by Dahpeht** [comment]
It was your input from https://bloodmallet.com/chart/hunter/marksmanship/trinkets/castingpatchwerk before all hunter data got wiped.

**Comment by Bloodmallet** [comment]
Ah right, I see. The profile was outdated, thus had broken talent strings after the patch. Nevertheless thank you for raising the issue!
