### ISSUE TITLE
Improve chart importer

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet_web_frontend#2]
Broken reports:
- https://dev.bloodmallet.com/chart/2e325e58-7ce0-44a5-bd4d-64ba1b4c7144
- https://dev.bloodmallet.com/chart/0c77520e-30b2-4036-862f-bb1d073d06b2

**Comment by Hollap-dev** [comment]
https://github.com/Bloodmallet/bloodmallet_web_frontend/pull/4/files
