### ISSUE TITLE
Dungeon trinket item levels

### ISSUE THREAD

**Issue by AyrinEU** [Bloodmallet/bloodmallet_web_frontend#39]
Dungeon trinkets are simmed at an incorrect item level, simmed at 223 when 226 would be expected to reflect the max item level from the Great Vault.

Affected trinkets found so far:
Phial of Putrefaction
Spare Meat Hook
Decanter of Anima-Charged Winds
Grim Codex
Blood-Spattered Scale
Viscera of Coalesced Hatred
Inscrutable Quantum Device
Overwhelming Power Crystal
Anima Field Emitter
Empyreal Ordnance
Sunblood Amethyst
Pulsating Stoneheart
Bladedancer's Armor Kit
Bottled Flayedwing Toxin
Infinitely Divisible Ooze
Overcharged Anima Battery
Mistcaller Ocarina
Shadowgrasp Totem
Sunblood Amethyst
Soulletting Ruby
Satchel of Misbegotten Minions
Overflowing Anima Cage
Siphoning Phylactery Shard
Lingering Sunmote
Boon of the Archon
Unbound Changeling
Vial of Spectral Essence

**Comment by Bloodmallet** [comment]
Thank you for the ticket. The backend got quite a few updates today especially for trinket itemlevels. Tomorrows data update should show some effect already.
