### ISSUE TITLE
Add back best races per class/spec 

### ISSUE THREAD

**Issue by gnarlygremlin** [Bloodmallet/bloodmallet_web_frontend#42]
as the title says, it was an extremely useful feature previously and means a lot for the min/maxers starting alts etc.

**Comment by Bloodmallet** [comment]
Greetings,
do you mean charts like this one? https://bloodmallet.com/chart/mage/fire/races/castingpatchwerk

If yes, the selection for different data types is now in a secondary top menu. See the following screenshot. 

![image](https://user-images.githubusercontent.com/9075987/101194920-f2026100-365e-11eb-9ed9-345143f7d388.png)

If this doesn't answer your question, please let me know.

**Comment by gnarlygremlin** [comment]
oh yeah exactly that, my bad. keep up the good work :)

**Comment by Bloodmallet** [comment]
Thank you for reaching out. I'm happy it's useful and I was able to help. Enjoy
