### ISSUE TITLE
make settings permanent

### ISSUE THREAD

**Issue by crialexyz** [Bloodmallet/bloodmallet_web_frontend#46]
hey!
I'm having problems saving settings in the web (bloodmallet web itself and wowhead item descriptions).
im from a spanish language country, but im used to do game stuff in english, but everytime i get into bloodmallet, its in spanish, then i have to go to settings and put english language, but that only works on the web language, but wowhead item descriptions keep showing in spanish.

I think it would be better if that language settings work on items descriptions as well, AND it keep being saved so we dont have to go to settings every time we want to check the site.

**Comment by Bloodmallet** [comment]
Greetings, thank you for the ticket. Yes, I'll be working on this.

**Comment by Bloodmallet** [comment]
Found a django setting that should make this pretty easy. Setting the duration of the language setting to 180 days for now.

**Comment by Bloodmallet** [comment]
Next release will have this improvement.

**Comment by crialexyz** [comment]
Hey!
I hope u had a Merry Christmas.
Thank you for all the great job you do.
