### ISSUE TITLE
Windwalker Legendaries don't work

### ISSUE THREAD

**Issue by VKupliauskis** [Bloodmallet/bloodmallet_web_frontend#52]
Trying to check legendaries for windwalker in Casting Patchwerk fails - console says:
` Cannot read property 'class' of undefined`
API call for the data responds with error:
`{"status": "error", "message": "No standard chart with these values found."}`

I assume there's an error on back-end

**Comment by Bloodmallet** [comment]
Thank you for the ticket. 
Seems to be working again: https://bloodmallet.com/chart/monk/windwalker/soul_binds/castingpatchwerk
