### ISSUE TITLE
Arms warrior execute buffs in patch 15/DEC

### ISSUE THREAD

**Issue by Lichteq** [Bloodmallet/bloodmallet_web_frontend#55]
Recent simulations are showing Venthyr behind the other covenants and I'm wondering whether the execute values have been updated for Bloodmallet soulbinds. 

Execute (non-venthyr) now hits for similar values as Condemn.

**Comment by Bloodmallet** [comment]
Sorry about the late response. I'm always using daily rebuilds of SimulationCraft. Therefore changes are picked up very quickly.
