### ISSUE TITLE
Chart issues/failures

### ISSUE THREAD

**Issue by Drathe** [Bloodmallet/bloodmallet_web_frontend#59]
So far, I have only noticed it on the Fury Warrior Trinket page, but there are some cases where it seems pretty obvious that something went wrong with the charts - unsure if it's a problem with the chart itself or the data. Screenshot attached.

![1](https://user-images.githubusercontent.com/42984832/105086063-acf78a00-5a66-11eb-8771-bec4afbea33c.png)

**Comment by Bloodmallet** [comment]
Greetings,
I'm aware of this Fury Warrior issue. Sadly debugging didn't yet reveal why some simulations suddenly lose dps. The visual breaks on such loss and then shows the loss as an incredible increase for the next itemlevel.

I'm on it.

**Comment by Bloodmallet** [comment]
Greetings, 
This issue should now be fixed. It was caused by "negative" dps increases. That made the charts visually overvalue the follow-up profile tremendously.
Such negative values are now corrected to be dps neutral.
