### ISSUE TITLE
Persist user selection for "auto-remove oldest chart"

### ISSUE THREAD

**Issue by vpicone** [Bloodmallet/bloodmallet_web_frontend#60]
This could also be a setting in someone's profile. Although I think a simple preference saved in local storage would be totally fine.

It can be frustrating to get the same error 2 or three times in a row when you forget to check the box.

**Comment by Bloodmallet** [comment]
Good call, will look into it.

**Comment by Bloodmallet** [comment]
Field is now auto-toggled
