### ISSUE TITLE
Icebringer for Frost Mage Hectic Add Cleave

### ISSUE THREAD

**Issue by pyrozr** [Bloodmallet/bloodmallet_web_frontend#61]
Currently the talent sim for frost mages is using the Single target legendary Frostburn for siming talents on Hectic add cleave and not the preferred legendary Icebringer and I think this has a massive effect on simulations for frost talents.

**Comment by Bloodmallet** [comment]
Greetings,
used profiles are those that SimulationCraft provides. I'm not changing such profiles. Please reach out to your class maintainers if you deem the profile to be improvable.
