### ISSUE TITLE
Wrong talent for Balance druid character profile

### ISSUE THREAD

**Issue by derickso** [Bloodmallet/bloodmallet_web_frontend#66]
Balance druid is currently using Force of Nature for T1 talent when Nature's Balance should be used

**Comment by Bloodmallet** [comment]
Greetings,
I'm using SimulationCrafts standard profiles. If a talent is wrong in a chart it can be changed by adjusting the base profiles in SimulationCraft. Reach out to your specs SimulationCraft maintainer. They are usually in class discords.
