### ISSUE TITLE
Warlock Trinket Sims

### ISSUE THREAD

**Issue by dtdowning** [Bloodmallet/bloodmallet_web_frontend#68]
I love your information and i appreciate all the helpful things u provide. I would like to add that in the warlock community we don't trust ur sims and they are not accurate to gameplay. example: glyph of assimilation is simming as our second highest trinket for affliciton, in actual practice, it is not. I bring this up cuz i think a lot of new people will not get an accurate picture as to what is doing the most damage.... also i believe the sim is including the glyph's mastery proc or something cuz it does not perform as well as it sims and a lot of people are going to receive wrong information on trinkets. again ty for all ur info, no hate all love, just some helpful feedback.

**Comment by Bloodmallet** [comment]
Greetings,
I'm just straight up using SimulationCraft to generate the results. So if you can't trust my charts SimulationCraft and therefore Raidbots will look forward to improvements to fix whatever might be wrong as well.

If you know more specifically what is wrong, please let me know.
