### ISSUE TITLE
Sinful Aspirant's Badge of Ferocity doesn't exist above ilvl 197.

### ISSUE THREAD

**Issue by crashin2life** [Bloodmallet/bloodmallet_web_frontend#69]
The title says it all. There is a different trinket, Sinful Gladiator's Badge of Ferocity that is available from conquest, which does go to that level, but the trinket sims imply that both trinkets can progress up to 226.

**Comment by Bloodmallet** [comment]
Thank you for the information. I'll fix that. Do you know how pvp itemlevels will be in 9.1?
