### ISSUE TITLE
Vulpera MM Hunter Hectic Add Cleave

### ISSUE THREAD

**Issue by Morynne** [Bloodmallet/bloodmallet_web_frontend#70]
There is nothing in Vulpera kit that would rank them that high. Their only ability that affects dps is single target only.
So is this a bug or I don't see something?

**Comment by Bloodmallet** [comment]
I'm not changing anything specific for Vulpera. If something strange is happening for them, that might be a SimulationCraft thing. I'm closing this ticket, but feel free to reopen it, if you have more information about this case.
