### ISSUE TITLE
Necrolord Feral using suboptimal talents

### ISSUE THREAD

**Issue by Hrolfger** [Bloodmallet/bloodmallet_web_frontend#71]
The optimal talent setup for ST PvE necroferal is Lunar Inspiration, Savage Roar, Brutal Slash and Feral Frenzy.
For hectic add cleave it becomes Predator, SR, Primal Wrath and Blood Talons.

Necrolord's Adaptive Swarm opens up for a completely different build/playstyle, having the sims done for trinkets/conduits match that build rather than a "less effective" variation of the Bitespam build that Nfae, Kyrian and Venthyr uses.

**Comment by Bloodmallet** [comment]
Greetings,
baseline profiles are extracted from SimulationCraft baseline profiles. If you want to adjust the used talents reach out to your specs maintainer, usually present in class discords.

If your spec requires special cases/handling for a specific covenant you can provide a special-case profile.
