### ISSUE TITLE
Warrior fury legendaries wrong values Cleave/ST

### ISSUE THREAD

**Issue by Squaqua** [Bloodmallet/bloodmallet_web_frontend#74]
The values about the new legendary of the fury warrior seems not right (atleast for the nf one) + The kyrian/necro has no value. 
![Leg capture](https://user-images.githubusercontent.com/87127630/124912894-c7122e00-dfee-11eb-89ce-d4f040add73b.JPG)

**Comment by Bloodmallet** [comment]
Greetings,
the visual of the chart was upgraded to now show the used baseline profiles properly. So now it should be clear, that currently no other covenant profile apart from the Venthyr baseline was found.
