### ISSUE TITLE
Rogue Legendary "Obedience" Showing Incorrect Values

### ISSUE THREAD

**Issue by dzdnconfuzd** [Bloodmallet/bloodmallet_web_frontend#77]
The description still has the old description of versatility increases at 1% instead of the changes that went live on July 13th, 2021 with 0.5%

**Comment by Bloodmallet** [comment]
Greetings,
tooltips are handled by wowhead. Which value is shown is somewhat out of my hands. Thank you for letting me know.
I'm closing this issue.
