### ISSUE TITLE
Domination shards and spe

### ISSUE THREAD

**Issue by 19marine91** [Bloodmallet/bloodmallet_web_frontend#78]
hi !

In mage arcane > Domination shards, the graphic is wrong or just the legend. Indeed, the 3 captions are : blood, frost and unholy (so, it's dk). And this issue is visible for several class (all maybe).

I hope my explanation and screenshot can help.

Thank you for every thing 

![Capture d’écran 2021-07-17 à 20 15 03](https://user-images.githubusercontent.com/87581385/126046177-0e0ce284-baa8-429f-8ba4-e887c2c4e282.png)

**Comment by Bloodmallet** [comment]
Greetings,
"blood", "frost", and "unholy" are the type of shards. As you might've seen already there are three distinct shard set bonuses available. Those require three of the same shard type to be socketed. Each shard type has 1 dps shard. Each shard has multiple upgradeably levels. What you see here are all dps shard and their upgradeable levels. And for convenience the chart tells you which shard is part of which set.
