### ISSUE TITLE
Soul Cage Fragment - Incorrect ilvl

### ISSUE THREAD

**Issue by SidonisAntares** [Bloodmallet/bloodmallet_web_frontend#79]
Item is listing on site as an ilvl 210 version, when Mor'geth drops a 233 ilvl version. 

![image](https://user-images.githubusercontent.com/18095891/126454238-2ee0aa7c-99d8-4955-aa05-52406de9dc0b.png)

**Comment by Bloodmallet** [comment]
Thank you for the report. This issue should be fixed.
