### ISSUE TITLE
[Dev] Chart bar mouseover background color

### ISSUE THREAD

**Issue by scamille** [Bloodmallet/bloodmallet_web_frontend#8]
It looks like the background color of the mouseover info is missing on the dev site, compared to the live site.

This makes reading the numbers very hard.

Site:
https://dev.bloodmallet.com/index#monk_windwalker
https://bloodmallet.com/index.html#monk_windwalker
Browser: Firefox 74.0

![bloodmallet_mouseOverBackground1](https://user-images.githubusercontent.com/1479348/77247216-2cda7b00-6c2f-11ea-9ac2-e4a49d517c24.PNG)

![bloodmallet_mouseOverBackground2](https://user-images.githubusercontent.com/1479348/77247219-2fd56b80-6c2f-11ea-8fe1-ab8b81e8c8c2.PNG)

**Comment by Bloodmallet** [comment]
Greetings,
yes the importer needs to get some updates, it got on the normal website over the course of the last year, too.

**Comment by Bloodmallet** [comment]
woops, automation can sometimes be annoying. I think this issue is now fixed with the release of this commit
