### ISSUE TITLE
Miniscule Mailemental in an Envelope Trinket

### ISSUE THREAD

**Issue by AhoyThere** [Bloodmallet/bloodmallet_web_frontend#80]
It's listed as one of the better Trinkets when looking at Assa Rogues. Could that be wrong since the Trinket says "Ranged Attacks"?  :)

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out about this issue.
This might be the case. The class mask for the trinket suggests that it's available for all specs. Please let me know if this is not the case (e.g. that it doesn't proc even though you were traded the trinket).
