### ISSUE TITLE
Fury legendaries

### ISSUE THREAD

**Issue by Voxxel** [Bloodmallet/bloodmallet_web_frontend#81]
Hi, 
I'm looking for a simple way to list Legendaries for my Kyrian Fury warrior but on the Legendaries page the list is only for Venthyrs.

How can I switch the covenant type here?

**Comment by Bloodmallet** [comment]
Greetings,
you can't switch the used profiles in the web-interface. If Warriors would have multiple covenant profiles in SimulationCraft or would submit fallback profiles to `bloodytools` I could show the other covenant specific legendaries or warriors properly (see Shadow Priest as an example).

You also could create your own charts with your own character profile by becoming a Patron.

**Comment by Voxxel** [comment]
I'm not after convenant-specific legendaries but just other common legendaries such as Signet of the Torment Kings, Deathmaker, etc. 

I would like to see a value chart for these common (shared) warrior leggos, similar to the list that available for Ventyr warriors here: 
https://bloodmallet.com/chart/warrior/fury/legendaries/castingpatchwerk
It is obvious that those legendaries produce different values for a Venthyr warrior than lets say a Kyrian warrior. The hierarchy chart would look quite different for each covenants.

**Comment by Bloodmallet** [comment]
Greetings,
I see. In that case no that's not possible in the standard charts. If you're a patron you can create your own custom charts with your character input, thus enabling you to see the worth of whatever covenant you have.
