### ISSUE TITLE
Havoc DH Soulbind, Mikanikos is missing a potency conduit

### ISSUE THREAD

**Issue by koticgood** [Bloodmallet/bloodmallet_web_frontend#82]
Not sure if this applies to the sim itself, or just the list.

When looking at renown-capped Mikanikos for Havoc DH, neither Hammer of Genesis or the Potency conduit you can take in the same row is displayed in the list.

Vengeance is fine; Hammer is listed for Hectic Add cleave and Potency conduit is listed for Patchwerk. But in those slots for Havoc, nothing is listed.

**Comment by Bloodmallet** [comment]
Greetings,
I can't reproduce what you're describing. I'm seeing Hammer of Genesis there. Could you have another look please? (I didn't change anything related to your question)
![grafik](https://user-images.githubusercontent.com/9075987/127774040-9c55c1ad-0b80-4eb2-a8f4-30bb757ef99c.png)
