### ISSUE TITLE
Custom Soulbind and Legendary charts of specs with covenant specific will see their not-their-covenants over-performing

### ISSUE THREAD

**Issue by Valedikay** [Bloodmallet/bloodmallet_web_frontend#86]
As you said yourself : "Custom Soulbind and Legendary charts of specs with covenant specific profiles either as fallback profiles in bloodytools or in SimulationCraft will see their not-their-covenants over-performing because those covenant specific profiles will most likely have a lot better gear than your character does"

EDIT : On Frost DK personal chart, it's 'bugging' when i put Kyrian covenant as mine, but it's quite accurate when i put Necrolord covenant in the simc text-file.

**Comment by Bloodmallet** [comment]
Greetings,
a fix is on the way. worker rebuilding in ~2h will introduce it.
