### ISSUE TITLE
Fragments of the Elder Antlers Legendary sim bug

### ISSUE THREAD

**Issue by Kiriestus** [Bloodmallet/bloodmallet_web_frontend#87]
Hello! I was looking at the numbers for BM hunter legendary sims and it the page at https://bloodmallet.com/chart/hunter/beast_mastery/legendaries/castingpatchwerk lists it as effectively doing 0 damage as compared to no legendary at all.  It seems to also not be calculated correctly for either MM or Survival. Thanks!

Edit - Realizing now that this happens with all covenant legendaries not associated with the covenant the sim was run in... is there any way to change to selected covenant on the website to see how this legendary should perform?

**Comment by Bloodmallet** [comment]
Greetings,
if a spec provides covenant specific profiles either in simulationcraft or as fallback profiles to my backend, then those legendaries will be simulated with appropriate profiles.
