### ISSUE TITLE
Legion Timewalking trinkets

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet_web_frontend#91]
Spiked Counterweight 136715
Nightmare Eggshell 137312
Mark of Dargrul 137357
Giant Ornamental Pearl 137369
Windscar Whetstone 137486
Faulty Countermeasure 137539
Tempered Egg of Serpentrix 137373
Tirathon's Betrayal 137537
Caged Horror 136716
Corrupted Starlight 137301
Oakheart's Gnarled Root 137306
Naraxas' Spiked Tongue 137349
Stormsinger Fulmination Charge 137367
Infernal Writ 137485
Moonlit Prism 137641

See [discord message](https://discord.com/channels/378523252923826187/378523252923826189/921529933417812039)

**Comment by Twiskir** [comment]
1 month celebrate comment

**Comment by Bloodmallet** [comment]
Legion timewalking trinkets are now available on the website. If something is strange about them, please open a new ticket.
