### ISSUE TITLE
DH Talent Tree

### ISSUE THREAD

**Issue by ChrisFZa** [Bloodmallet/bloodmallet_web_frontend#97]
In the Class talent tree, bottom left, below Chaos nova there have been changes. 
1. Illidari Knowledge is missing
2. Internal Struggle is below Chaos Nova.
![wowheadDH](https://user-images.githubusercontent.com/54979749/198024955-dd7c406c-bbdb-4246-8e82-95273b3ecb6c.png)

**Comment by Bloodmallet** [comment]
Thank you for reaching out. The development of our own talent trees is halted for now. I'm closing this ticket for now.
