### ISSUE TITLE
New Races for Rogue's has not been added.

### ISSUE THREAD

**Issue by Shamainy** [Bloodmallet/bloodmallet_web_frontend#99]
Draenei Rogue
Highmountain Tauren Rogue
Lightforged Draenei Rogue
Tauren Rogue

The above are currently not being simmed and has not been added the simulation type Races for rogues when simming a chart for it.

**Comment by Bloodmallet** [comment]
Thank you for pointing this out. I'll look into adding them.

**Comment by Bloodmallet** [comment]
This should be fixed by now. Closing the ticket.
